# Generated by Django 4.2.3 on 2023-08-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoanAmount', models.IntegerField(blank=True, null=True)),
                ('LoanDate', models.DateField()),
                ('ExperyDate', models.DateField()),
                ('MonthlyCut_percentage', models.IntegerField(blank=True, null=True)),
                ('MonthlyCut_Amount', models.IntegerField(blank=True, null=True)),
                ('Note', models.TextField(max_length=100)),
                ('File', models.FileField(default='', upload_to='loanfile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee')),
            ],
        ),
    ]
