# Generated by Django 4.2.3 on 2023-08-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_employeeloan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloan',
            name='ExperyDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='LoanDate',
            field=models.CharField(max_length=100),
        ),
    ]
