# Generated by Django 4.2.3 on 2023-09-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_employeeloan_experydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='action',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='File',
            field=models.FileField(blank=True, default='', null=True, upload_to='loanfile'),
        ),
    ]
