# Generated by Django 4.2.3 on 2023-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_invoice_baldue_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='adjustment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
