# Generated by Django 4.2.3 on 2023-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_challan_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='adjustment',
            field=models.FloatField(),
        ),
    ]
